# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd52d7d4946b3a250ec1f2e56e7700a1dcf1752e1be33b7809e905a4a61466f0471f7f7c819f165363836d9ce256b40624e4b921c443faa51a7a1d191a7bcbab

test:
  secret_key_base: 5bd5fb3329b60396a82a44a4b22ccac2ff967bb1d8f9a098a9533f00e474ccc81d4cf291a71ef0cb3740f2e3a766be257f0be8375960be6ad2ab61af04be8a9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
